test:
	ncverilog cma.v PE_ARRAY.v COL_reg3.v PE_withReg_onlyNN.v PE_withReg_allN.v ALU.v ALU_SEL.v FUNC.v SE.v PRIMITIVE.v CONF_CONST_CTRL.v CONF_CTRL.v CONST_CTRL.v mc.v ifex.v imem.v rfile.v ldadd.v ldtbl.v stadd.v dbank.v bank.v dmanu8.v dmem.v DIV.v
